apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webrtclixir.fullname" . }}
  namespace: beep-webrtc
  labels:
    {{- include "webrtclixir.labels" . | nindent 4 }}
  annotations:
    trivy.registry/harbor.polytech.umontpellier.fr: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webrtclixir.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webrtclixir.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        - name: beep-registry
      serviceAccountName: {{ include "webrtclixir.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          annotations:
            trivy.registry/harbor.polytech.umontpellier.fr: "true"
          env:
          - name: PORT
            value: "8080"
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: webrtclixir-secret
                key: secret-key-base
          - name: PHX_HOST
            value: {{ .Values.env.phxHost }}
          - name: ADMIN_USERNAME
            value: {{ .Values.env.adminUsername }}
          - name: ADMIN_PASSWORD
            value: {{ .Values.env.adminPassword }}
          - name: ICE_PORT_RANGE
            value: {{ .Values.env.icePortRange }}
          - name: PHX_SERVER
            value: "1"
          - name: NEXUS_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
