replicaCount: 1
image:
  pullPolicy: Always
  portHTTP: 8080
  portUDPmin: 5060
  portUDPmax: 5060
  ipEndpoint: 162.38.112.211

service:
  type: ClusterIP
  port: 80

resources: {}
ports:
  - 5060

appSecretName: app-secret